name: Docker Publish
on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/tp-docker-symphony:1.0.0
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/tp-docker-symphony:1.0.0
